// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLaOsGvVwW6hDJ11PHKsHTkbm6naLaltk',
    appId: '1:846806930942:web:bb753a54dc4e86606d1caf',
    messagingSenderId: '846806930942',
    projectId: 'eventfest-part-one',
    authDomain: 'eventfest-part-one.firebaseapp.com',
    storageBucket: 'eventfest-part-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGXc-m4tX9d0i5_bCPzllvmLgjB6tkKb4',
    appId: '1:846806930942:android:b04af7bdf4046f1b6d1caf',
    messagingSenderId: '846806930942',
    projectId: 'eventfest-part-one',
    storageBucket: 'eventfest-part-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOVXVLok6w7pl3ZfKsi5vhSCWChQQtqg',
    appId: '1:846806930942:ios:8817f402fea742726d1caf',
    messagingSenderId: '846806930942',
    projectId: 'eventfest-part-one',
    storageBucket: 'eventfest-part-one.appspot.com',
    iosBundleId: 'com.example.eventmainapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrOVXVLok6w7pl3ZfKsi5vhSCWChQQtqg',
    appId: '1:846806930942:ios:745994209412e2fb6d1caf',
    messagingSenderId: '846806930942',
    projectId: 'eventfest-part-one',
    storageBucket: 'eventfest-part-one.appspot.com',
    iosBundleId: 'com.example.eventmainapp.RunnerTests',
  );
}
